<?php
namespace Sdkit\Sdkit\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SdkitCommand extends Command
{
    const NAME_ARG = 'name';

    protected function configure()
    {
        $this->setName('sdkit:sdkit')
            ->setDescription('Sdkit Magento Command')
            ->setDefinition( [ new InputArgument(self::NAME_ARG, InputArgument::OPTIONAL, 'Name')] );
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $name = $input->getArgument('name');
        $output->writeln( sprintf("Hello %s ", $name ));
//        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
